# Site settings
title: Tools for Information Literacy 
subtitle: "INLS161-002 Fall 2016"
description: "Tools and concepts for information literacy. Includes software use and maintenance, computer applications, and networked information systems."
baseurl: /inls161fall2016
#baseurl: "http://ils.unc.edu/courses/2016_summerII/inls161_001"
url:
#url: http://ils.unc.edu/courses/2016_summerII/inls161_001/

#name: John D. Martin III
#email: john.d.martin.iii@unc.edu
#twitter_username: jdmar3
#github_username:  jdmar3

department: INLS
course-number: "161"
course-section: "002"
course-term: Fall
course-year: "2016"
dates: 24 August 2016 - 7 December 2016
exam: 10 December 2016 4:00 PM

# When mothballed, assignments link to assignments/a#.md 
mothballed: false

acknowledgements: I would like to thank John D. Martin III and Ron Bergquist, upon whose courses much of the content of this course is based, as well as the other instructors of INLS 161 who've been instrumental in making the course into what it is today. 

credits: This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using a slightly modified version of the <a href="https://github.com/jasonlong/architect-theme">Architect theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>. <a href="https://github.com/pietromenna/jekyll-architect-theme">jekyll-architect-theme</a> is maintained by <a href="https://github.com/pietromenna">pietromenna</a>.

# Build settings

future: true

#markdown: kramdown
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "superscript"]

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/New_York

excerpt_separator: <excerpt/>  # you can specify your own separator, of course.

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/workspace/jdmar3.github.io